name: Pull Request Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    needs: [prettier, vitest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Actualizar Node a 22.11.0
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 22.11.0

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm run build

  vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Actualizar Node a 22.11.0
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 22.11.0

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm run test

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Actualizar Node a 22.11.0
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 22.11.0

      - name: Instalar Prettier
        run: npm install -g prettier

      - name: Ejecutar Prettier
        run: prettier --check .
